CREATE MATERIALIZED VIEW LOG ON sa_customers.sa_transaction
WITH rowid, SEQUENCE (FIRST_NAME, LAST_NAME, PRODUCT_NAME, LINE_NAME, COLLECTION_NAME, SIZE_CLOTHES, PRICE,
PROMOTION, VALID_FROM, VALID_TO, PRICE_PERCENT,DATE_TRANSACTION, GEO)
INCLUDING NEW VALUES;