drop TABLE DW_CL_CUSTOMERS_DATA ;
CREATE TABLE DW_CL_CUSTOMERS_DATA 
(
    first_name    VARCHAR2(40 BYTE) NOT NULL,
    last_name     VARCHAR2(40 BYTE) NOT NULL,
    email         VARCHAR2(50 BYTE) NOT NULL,
    phone         VARCHAR2(40 BYTE) NOT NULL,
    age           NUMBER(3) NOT NULL,
    INSERT_DATE   DATE NOT NULL)
TABLESPACE ts_DW_CL;
drop TABLE DW_CL_STORE_DATA  ;
CREATE TABLE DW_CL_STORE_DATA 
(
    STORE_PHONE       VARCHAR2(40 BYTE) NOT NULL,
    STORE_NAME        VARCHAR2(50 BYTE) NOT NULL,
    INSERT_DATE       DATE NOT NULL)
TABLESPACE ts_DW_CL;

DROP TABLE DW_CL_PRODUCT_DATA;
CREATE TABLE DW_CL_PRODUCT_DATA 
(
    PRODUCT_NAME      VARCHAR2(40 BYTE) NOT NULL,
    LINE_ID           INT NOT NULL,
    LINE_NAME         VARCHAR2(40 BYTE) NOT NULL,
    COLLECTION_ID     INT NOT NULL,
    COLLECTION_NAME   VARCHAR2(40 BYTE) NOT NULL,
    SEASON_ID         INT NOT NULL,
    SEASON            VARCHAR2(40 BYTE) NOT NULL,
    SIZE_CLOTHES      VARCHAR2(10 BYTE) NOT NULL,
    COLOR             VARCHAR2(40 BYTE) NOT NULL,
    PRICE             FLOAT NOT NULL,
    INSERT_DATE       DATE NOT NULL)
TABLESPACE ts_DW_CL;

DROP TABLE DW_CL_GEN_PROMOTION_DATA ;
CREATE TABLE DW_CL_GEN_PROMOTION_DATA 
(
    PROMOTION     VARCHAR2(40 BYTE),
    VALID_FROM    date not null,
    VALID_TO      date NOT NULL,
    INSERT_DAY    date NOT NULL,
    PRICE_PERCENT float NOT NULL)
TABLESPACE ts_DW_CL;

DROP TABLE DW_CL_TRANSACTION; 
CREATE TABLE DW_CL_TRANSACTION
(
    first_name    VARCHAR2(40 BYTE),
    last_name     VARCHAR2(40 BYTE),
    PRODUCT_NAME        VARCHAR2(40 BYTE) NOT NULL,
    LINE_NAME         VARCHAR2(40 BYTE) NOT NULL,
    COLLECTION_NAME   VARCHAR2(40 BYTE) NOT NULL,
    SIZE_CLOTHES      VARCHAR2(10 BYTE) NOT NULL,
    PRICE             FLOAT NOT NULL,
    PROMOTION     VARCHAR2(40 BYTE),
    VALID_FROM    date not null,
    VALID_TO      date NOT NULL,
    PRICE_PERCENT float NOT NULL,
    DATE_TRANSACTION DATE NOT NULL,
    GEO INT NOT NULL)
TABLESPACE ts_DW_CL;

DROP TABLE DW_CL_period_DATA ;
CREATE TABLE DW_CL_period_DATA 
(
    START_PERIOD  INT NOT NULL,
    END_PERIOD    INT ,
    INSERT_DAY    date NOT NULL,
    update_day    date)
TABLESPACE ts_DW_CL;

select count(*) from DW_CL_TRANSACTION;
select count(*) from DW_CL_CUSTOMERS_DATA ;