CREATE TABLESPACE GEO_BACKUP
DATAFILE '/oracle/u01/app/oracle/oradata/DCORCL/pdb_asadovskaya/db_qpt_sb_m.dat'
SIZE 150M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 
CREATE USER user_backup
IDENTIFIED BY "%PWD%"
DEFAULT TABLESPACE GEO_BACKUP;


GRANT CONNECT,RESOURCE TO user_backup;
GRANT SELECT ANY TABLE TO user_backup;

ALTER USER user_backup QUOTA UNLIMITED ON GEO_BACKUP;