begin
    Pkg_etl_customers_cl.load_CLEAN_CUSTOMER;
    pkg_etl_products_cl.load_CLEAN_product;
    pkg_etl_period_cl.load_CLEAN_period_DATA;
    pkg_etl_promotions_cl.load_CLEAN_GEN_PROMOTION_DATA;
    pkg_etl_store_cl.load_CLEAN_store;
    pkg_etl_transaction_def.load_CLEAN_transaction;
    pkg_etl_store_dw_stage.load_stores_dw;
    pkg_etl_customers_dw_stage.load_customers_dw;
    pkg_etl_products_dw_stage.load_products_dw;
    pkg_etl_periods_dw_stage.load_period_data;
    pkg_etl_dw_promotion_def.load_PROMOTION_types;
    pkg_etl_dw_promotion_def.load_PROMOTION_hist;
    pkg_etl_transaction_dw.load_transaction_dw;
    pkg_etl_product_dim.load_product_dim;
    pkg_etl_promotion_dim.load_PROMOTION_dim;
end;