TRUNCATE TABLE DW_CL.DW_CL_GEN_PROMOTION_DATA;
TRUNCATE TABLE DW_CL.DW_CL_CUSTOMERS_DATA;
TRUNCATE TABLE DW_CL.DW_CL_PERIOD_DATA;
TRUNCATE TABLE DW_CL.DW_CL_PRODUCT_DATA;
TRUNCATE TABLE DW_CL.DW_CL_STORE_DATA;
TRUNCATE TABLE DW_CL.DW_CL_TRANSACTION;

TRUNCATE TABLE DW_DATA.DW_CUSTOMERS_DATA;
TRUNCATE TABLE DW_DATA.DW_PERIOD_DATA;
TRUNCATE TABLE DW_DATA.DW_GEN_PROMOTION_HIST;
TRUNCATE TABLE DW_DATA.DW_GEN_PROMOTION_TYPE;
TRUNCATE TABLE DW_DATA.DW_PRODUCT_DATA;
TRUNCATE TABLE DW_DATA.DW_STORE_DATA;
TRUNCATE TABLE DW_DATA.DW_TRANSACTION;
TRUNCATE TABLE DW_DATA.T_COUNTRY_FACT_SALES_DD;
TRUNCATE TABLE DW_DATA.T_RETAIL_FACT_SALES_DD;

TRUNCATE TABLE ALINA.COUNTRY_FACT_SALES_DD;
TRUNCATE TABLE ALINA.RETAIL_FACT_SALES_DD;
TRUNCATE TABLE ALINA.DIM_PRODUCT;
TRUNCATE TABLE ALINA.DIM_PROMOTIONS_SCD;


DROP SEQUENCE SEQ_CUSTOMERS;
CREATE SEQUENCE SEQ_CUSTOMERS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP SEQUENCE SEQ_STORES;
CREATE SEQUENCE SEQ_STORES
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP SEQUENCE SEQ_PRODUCTS;
CREATE SEQUENCE SEQ_PRODUCTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
drop SEQUENCE SEQ_PERIOD;
CREATE SEQUENCE SEQ_PERIOD
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP SEQUENCE SEQ_PROMOTION;
CREATE SEQUENCE SEQ_PROMOTION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP SEQUENCE SEQ_PROMOTION_hist; 
CREATE SEQUENCE SEQ_PROMOTION_hist
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP SEQUENCE SEQ_TRANSACTION;
CREATE SEQUENCE SEQ_TRANSACTION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
