DROP TABLE DW_CUSTOMERS_DATA;
CREATE TABLE DW_CUSTOMERS_DATA 
(
    CUSTOMER_ID   NUMBER(10) NOT NULL,
    first_name    VARCHAR2(40 BYTE) NOT NULL,
    last_name     VARCHAR2(40 BYTE) NOT NULL,
    email         VARCHAR2(50 BYTE) NOT NULL,
    phone         VARCHAR2(40 BYTE) NOT NULL,
    age           NUMBER(3) NOT NULL,
    INSERT_DATE   DATE NOT NULL,
    UPDATE_DATE   DATE)
TABLESPACE ts_DW_DATA_01;

ALTER TABLE DW_CUSTOMERS_DATA
   ADD CONSTRAINT PK_DW_CUSTOMERS_DATA PRIMARY KEY (CUSTOMER_ID);

DROP SEQUENCE SEQ_CUSTOMERS;
CREATE SEQUENCE SEQ_CUSTOMERS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
 DROP TABLE DW_STORE_DATA;
CREATE TABLE DW_STORE_DATA 
(
    STORE_ID          NUMBER(10) NOT NULL,
    STORE_PHONE       VARCHAR2(40 BYTE) NOT NULL,
    STORE_NAME        VARCHAR2(50 BYTE) NOT NULL,
    INSERT_DATE       DATE NOT NULL,
    UPDATE_DATE       DATE)
TABLESPACE ts_DW_DATA_01;

ALTER TABLE DW_STORE_DATA
   ADD CONSTRAINT PK_DW_STORE_DATA PRIMARY KEY (STORE_ID);

DROP SEQUENCE SEQ_STORES;
CREATE SEQUENCE SEQ_STORES
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE TABLE DW_PRODUCT_DATA 
(
    PRODUCT_ID          NUMBER(10) NOT NULL,
    PRODUCT_NAME      VARCHAR2(40 BYTE) NOT NULL,
    LINE_ID           INT NOT NULL,
    LINE_NAME         VARCHAR2(40 BYTE) NOT NULL,
    COLLECTION_ID     INT NOT NULL,
    COLLECTION_NAME   VARCHAR2(40 BYTE) NOT NULL,
    SEASON_ID         INT NOT NULL,
    SEASON            VARCHAR2(40 BYTE) NOT NULL,
    SIZE_CLOTHES      VARCHAR2(10 BYTE) NOT NULL,
    COLOR             VARCHAR2(40 BYTE) NOT NULL,
    PRICE             FLOAT NOT NULL,
    INSERT_DATE       DATE NOT NULL,
    UPDATE_DATE       DATE)
TABLESPACE ts_DW_DATA_01;

ALTER TABLE DW_PRODUCT_DATA
   ADD CONSTRAINT PK_DW_PRODUCT_DATA PRIMARY KEY (PRODUCT_ID);

DROP SEQUENCE SEQ_PRODUCTS;
CREATE SEQUENCE SEQ_PRODUCTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
drop table DW_period_DATA;
CREATE TABLE DW_period_DATA 
(
    PERIOD_ID     INT NOT NULL,
    START_PERIOD  INT NOT NULL,
    END_PERIOD    INT ,
    INSERT_DAY    date NOT NULL)
TABLESPACE ts_DW_DATA_01;

ALTER TABLE DW_period_DATA 
   ADD CONSTRAINT PK_DW_period_DATA  PRIMARY KEY (PERIOD_ID);

drop SEQUENCE SEQ_PERIOD;
CREATE SEQUENCE SEQ_PERIOD
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
drop TABLE DW_GEN_PROMOTION_TYPE ;
CREATE TABLE DW_GEN_PROMOTION_TYPE 
(
    PROMOTION_ID  INT NOT NULL,
    PROMOTION     VARCHAR2(40 BYTE),
    PRICE_PERCENT float NOT NULL,
    INSERT_DAY    date NOT NULL,
    UPDATE_DAY    DATE
    )
TABLESPACE ts_DW_DATA_01;

ALTER TABLE DW_GEN_PROMOTION_TYPE
   ADD CONSTRAINT PK_DW_GEN_PROMOTION_TYPE PRIMARY KEY (PROMOTION_ID);

DROP SEQUENCE SEQ_PROMOTION;
CREATE SEQUENCE SEQ_PROMOTION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP TABLE DW_GEN_PROMOTION_HIST;
CREATE TABLE DW_GEN_PROMOTION_HIST 
(
    PROMOTION_SURROGATE_KEY int NOT NULL,
    PROMOTION_ID  INT NOT NULL,
    PROMOTION     VARCHAR2(40 BYTE),
    PRICE_PERCENT float NOT NULL,
    VALID_FROM    date not null,
    VALID_TO      date NOT NULL,
    INSERT_DAY    date NOT NULL,
    UPDATE_DAY    DATE 
    )
TABLESPACE ts_DW_DATA_01;

CREATE SEQUENCE SEQ_PROMOTION_hist
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
ALTER TABLE DW_GEN_PROMOTION_HIST
   ADD CONSTRAINT PK_DW_GEN_PROMOTION_HIST PRIMARY KEY (PROMOTION_id,VALID_FROM,VALID_to);

DROP TABLE DW_TRANSACTION;
CREATE TABLE DW_TRANSACTION
(
    TRANSACTION_ID  INT ,
    customer_id     int not null,
    PRODUCT_id      int NOT NULL,
    PROMOTION_type_id    int not null,
    DATE_TRANSACTION DATE NOT NULL,
    period_id int not null,
    GEO INT NOT NULL)
TABLESPACE ts_DW_DATA_01;

DROP SEQUENCE SEQ_TRANSACTION;
CREATE SEQUENCE SEQ_TRANSACTION
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
ALTER TABLE DW_TRANSACTION
   ADD CONSTRAINT PK_DW_TRANSACTION PRIMARY KEY (TRANSACTION_ID);